import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class MyWorld here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class MyWorld extends World
{

    /**
     * Constructor for objects of class MyWorld.
     * 
     */
    public MyWorld()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(14, 14, 50); 
        prepare();
    }
    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {
        Bloque bloque = new Bloque();
        addObject(bloque,0,0);
        Bloque bloque2 = new Bloque();
        addObject(bloque2,2,0);
        bloque2.setLocation(2,0);
        Bloque bloque3 = new Bloque();
        addObject(bloque3,2,0);
        Bloque bloque4 = new Bloque();
        addObject(bloque4,1,0);
        Bloque bloque5 = new Bloque();
        addObject(bloque5,3,0);
        Bloque bloque6 = new Bloque();
        addObject(bloque6,4,0);
        Bloque bloque7 = new Bloque();
        addObject(bloque7,5,0);
        Bloque bloque8 = new Bloque();
        addObject(bloque8,6,0);
        Bloque bloque9 = new Bloque();
        addObject(bloque9,7,0);
        Bloque bloque10 = new Bloque();
        addObject(bloque10,8,0);
        Bloque bloque11 = new Bloque();
        addObject(bloque11,9,0);
        Bloque bloque12 = new Bloque();
        addObject(bloque12,10,0);
        Bloque bloque13 = new Bloque();
        addObject(bloque13,11,0);
        Bloque bloque14 = new Bloque();
        addObject(bloque14,12,0);
        Bloque bloque15 = new Bloque();
        addObject(bloque15,13,0);
        Bloque bloque16 = new Bloque();
        addObject(bloque16,0,1);
        Bloque bloque17 = new Bloque();
        addObject(bloque17,1,1);
        Bloque bloque18 = new Bloque();
        addObject(bloque18,2,1);
        Bloque bloque19 = new Bloque();
        addObject(bloque19,8,1);
        Bloque bloque20 = new Bloque();
        addObject(bloque20,9,1);
        Bloque bloque21 = new Bloque();
        addObject(bloque21,11,1);
        Bloque bloque22 = new Bloque();
        addObject(bloque22,12,1);
        Bloque bloque23 = new Bloque();
        addObject(bloque23,13,1);
        Bloque bloque24 = new Bloque();
        addObject(bloque24,4,2);
        Bloque bloque25 = new Bloque();
        addObject(bloque25,5,2);
        Bloque bloque26 = new Bloque();
        addObject(bloque26,6,2);
        Bloque bloque27 = new Bloque();
        addObject(bloque27,8,2);
        Bloque bloque28 = new Bloque();
        addObject(bloque28,11,2);
        Bloque bloque29 = new Bloque();
        addObject(bloque29,13,2);
        Bloque bloque30 = new Bloque();
        addObject(bloque30,0,3);
        Bloque bloque31 = new Bloque();
        addObject(bloque31,2,3);
        Bloque bloque32 = new Bloque();
        addObject(bloque32,3,3);
        Bloque bloque33 = new Bloque();
        addObject(bloque33,5,3);
        Bloque bloque34 = new Bloque();
        addObject(bloque34,8,3);
        Bloque bloque35 = new Bloque();
        addObject(bloque35,10,3);
        Bloque bloque36 = new Bloque();
        addObject(bloque36,11,3);
        Bloque bloque37 = new Bloque();
        addObject(bloque37,13,3);
        Bloque bloque38 = new Bloque();
        addObject(bloque38,0,4);
        Bloque bloque39 = new Bloque();
        addObject(bloque39,5,4);
        Bloque bloque40 = new Bloque();
        addObject(bloque40,7,4);
        Bloque bloque41 = new Bloque();
        addObject(bloque41,13,4);
        Bloque bloque42 = new Bloque();
        addObject(bloque42,0,5);
        Bloque bloque43 = new Bloque();
        addObject(bloque43,1,5);
        Bloque bloque44 = new Bloque();
        addObject(bloque44,3,5);
        Bloque bloque45 = new Bloque();
        addObject(bloque45,4,5);
        Bloque bloque46 = new Bloque();
        addObject(bloque46,7,5);
        Bloque bloque47 = new Bloque();
        addObject(bloque47,8,5);
        Bloque bloque48 = new Bloque();
        addObject(bloque48,9,5);
        Bloque bloque49 = new Bloque();
        addObject(bloque49,11,5);
        Bloque bloque50 = new Bloque();
        addObject(bloque50,12,5);
        Bloque bloque51 = new Bloque();
        addObject(bloque51,13,5);
        Bloque bloque52 = new Bloque();
        addObject(bloque52,0,6);
        Bloque bloque53 = new Bloque();
        addObject(bloque53,3,6);
        Bloque bloque54 = new Bloque();
        addObject(bloque54,4,6);
        Bloque bloque55 = new Bloque();
        addObject(bloque55,6,6);
        Bloque bloque56 = new Bloque();
        addObject(bloque56,13,6);
        Bloque bloque57 = new Bloque();
        addObject(bloque57,0,7);
        Bloque bloque58 = new Bloque();
        addObject(bloque58,2,7);
        Bloque bloque59 = new Bloque();
        addObject(bloque59,4,7);
        bloque59.setLocation(6,7);
        Bloque bloque60 = new Bloque();
        addObject(bloque60,6,7);
        bloque59.setLocation(6,7);
        Bloque bloque61 = new Bloque();
        addObject(bloque61,6,7);
        Bloque bloque62 = new Bloque();
        addObject(bloque62,4,7);
        Bloque bloque63 = new Bloque();
        addObject(bloque63,8,7);
        Bloque bloque64 = new Bloque();
        addObject(bloque64,9,7);
        Bloque bloque65 = new Bloque();
        addObject(bloque65,10,7);
        Bloque bloque66 = new Bloque();
        addObject(bloque66,11,7);
        Bloque bloque67 = new Bloque();
        addObject(bloque67,13,7);
        Bloque bloque68 = new Bloque();
        addObject(bloque68,0,8);
        Bloque bloque69 = new Bloque();
        addObject(bloque69,1,8);
        Bloque bloque70 = new Bloque();
        addObject(bloque70,6,8);
        Bloque bloque71 = new Bloque();
        addObject(bloque71,13,8);
        Bloque bloque72 = new Bloque();
        addObject(bloque72,0,9);
        Bloque bloque73 = new Bloque();
        addObject(bloque73,1,9);
        Bloque bloque74 = new Bloque();
        addObject(bloque74,3,9);
        Bloque bloque75 = new Bloque();
        addObject(bloque75,4,9);
        Bloque bloque76 = new Bloque();
        addObject(bloque76,5,9);
        Bloque bloque77 = new Bloque();
        addObject(bloque77,6,9);
        Bloque bloque78 = new Bloque();
        addObject(bloque78,7,9);
        Bloque bloque79 = new Bloque();
        addObject(bloque79,9,9);
        Bloque bloque80 = new Bloque();
        addObject(bloque80,11,9);
        Bloque bloque81 = new Bloque();
        addObject(bloque81,12,9);
        Bloque bloque82 = new Bloque();
        addObject(bloque82,13,9);
        Bloque bloque83 = new Bloque();
        addObject(bloque83,0,10);
        Bloque bloque84 = new Bloque();
        addObject(bloque84,1,10);
        Bloque bloque85 = new Bloque();
        addObject(bloque85,4,10);
        Bloque bloque86 = new Bloque();
        addObject(bloque86,10,10);
        Bloque bloque87 = new Bloque();
        addObject(bloque87,0,11);
        Bloque bloque88 = new Bloque();
        addObject(bloque88,2,11);
        Bloque bloque89 = new Bloque();
        addObject(bloque89,4,11);
        Bloque bloque90 = new Bloque();
        addObject(bloque90,6,11);
        Bloque bloque91 = new Bloque();
        addObject(bloque91,7,11);
        Bloque bloque92 = new Bloque();
        addObject(bloque92,9,11);
        Bloque bloque93 = new Bloque();
        addObject(bloque93,10,11);
        Bloque bloque94 = new Bloque();
        addObject(bloque94,12,11);
        Bloque bloque95 = new Bloque();
        addObject(bloque95,13,11);
        Bloque bloque96 = new Bloque();
        addObject(bloque96,0,12);
        Bloque bloque97 = new Bloque();
        addObject(bloque97,0,13);
        Bloque bloque98 = new Bloque();
        addObject(bloque98,6,12);
        Bloque bloque99 = new Bloque();
        addObject(bloque99,13,12);
        Bloque bloque100 = new Bloque();
        addObject(bloque100,2,13);
        bloque100.setLocation(2,13);
        Bloque bloque101 = new Bloque();
        addObject(bloque101,2,13);
        Bloque bloque102 = new Bloque();
        addObject(bloque102,1,13);
        Bloque bloque103 = new Bloque();
        addObject(bloque103,3,13);
        Bloque bloque104 = new Bloque();
        addObject(bloque104,4,13);
        Bloque bloque105 = new Bloque();
        addObject(bloque105,5,13);
        Bloque bloque106 = new Bloque();
        addObject(bloque106,6,13);
        Bloque bloque107 = new Bloque();
        addObject(bloque107,7,13);
        Bloque bloque108 = new Bloque();
        addObject(bloque108,8,13);
        Bloque bloque109 = new Bloque();
        addObject(bloque109,10,13);
        Bloque bloque110 = new Bloque();
        addObject(bloque110,9,13);
        Bloque bloque111 = new Bloque();
        addObject(bloque111,11,13);
        Bloque bloque112 = new Bloque();
        addObject(bloque112,12,13);
        Bloque bloque113 = new Bloque();
        addObject(bloque113,13,13);
        Mochi mochi = new Mochi();
        addObject(mochi,0,2);
        Arándano arándano = new Arándano();
        addObject(arándano,3,1);
        Arándano arándano2 = new Arándano();
        addObject(arándano2,10,1);
        Arándano arándano3 = new Arándano();
        addObject(arándano3,3,7);
        Arándano arándano4 = new Arándano();
        addObject(arándano4,1,12);
        Arándano arándano5 = new Arándano();
        addObject(arándano5,12,8);
        Banano banano = new Banano();
        addObject(banano,1,3);
        Banano banano2 = new Banano();
        addObject(banano2,1,7);
        Banano banano3 = new Banano();
        addObject(banano3,7,1);
        Banano banano4 = new Banano();
        addObject(banano4,5,5);
        Banano banano5 = new Banano();
        addObject(banano5,5,10);
        Banano banano6 = new Banano();
        addObject(banano6,2,9);
        Banano banano7 = new Banano();
        addObject(banano7,10,6);
        Banano banano8 = new Banano();
        addObject(banano8,10,9);
        Banano banano9 = new Banano();
        addObject(banano9,8,11);
        Cereza cereza = new Cereza();
        addObject(cereza,13,10);
        Cereza cereza2 = new Cereza();
        addObject(cereza2,12,2);
        Cereza cereza3 = new Cereza();
        addObject(cereza3,10,12);
        Cereza cereza4 = new Cereza();
        addObject(cereza4,4,3);
    }
}
